stages:
  - build

build:
  stage: build
  image: node:20.14.0
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./dist/spa/**
    expire_in: 1 week
  rules:
    - when: manual
  allow_failure: false
